"""RAGpilot: a local-first knowledge compiler and retrieval engine."""

try:
    from ragpilot._version import __version__
except ImportError:
    # `_version.py` is generated by hatch-vcs at build/install time from
    # the nearest git tag (see pyproject.toml's [tool.hatch.version]/
    # [tool.hatch.build.hooks.vcs]) -- missing only for a raw source
    # checkout that was never installed at all. Never a hard failure just
    # to report a version string.
    __version__ = "0+unknown"
